### PR TITLE
Restore compatibility with Python 2

### PR DESCRIPTION
**Pull request by gergondet**
This PR includes pybind11-2.9.2 (the last version to support Python 2) to allow to continue to use Choreonoid with Python 2 for the time being.

It also includes a commit that fixes an incremental build issue introduced by 4d334a1813cb5c5e5365dc696b169916b61d55d4

### CODE REVIEW

**Comment by gergondet** [comment]
@s-nakaoka Sorry for bumping this but could you give it a look? Thanks

**Comment by s-nakaoka** [comment]
Sorry for the delay in responding. Thank you for bumping this.

I could do it this way, but I'm a bit hesitant about bundling two versions of pybind11 for the old Python2, so I'm wondering if you could turn off USE_BUNDLED_PYBIND11 and use pybind11_DIR to specify the externally installed pybind11-2.9.2. How about this?

**Comment by gergondet** [comment]
Thanks for the feedback. That makes sense and I adopted this approach.

I'll close this PR but could you consider cherry-picking [`8e89cf0` (#30)](https://github.com/choreonoid/choreonoid/pull/30/commits/8e89cf062536f712e29967b9cb28f8517f0394b6) which is not related to this?

**Comment by s-nakaoka** [comment]
I have cherry-picked 8e89cf062536f712e29967b9cb28f8517f0394b6 .
Thank you for your cooperation.

**Pull request closed without merging**
